<template>
  <div class="locations-container">
    <div class="dropdown-container">
      <label for="highway">Highway</label>
      <select name="highway">
        <option value="i-65">I-65</option>
<option value="i-22">I-22</option>
<option value="i-10">I-10</option>
<option value="i-20">I-20</option>
<option value="hwy 72a">Hwy 72A</option>
<option value="hwy 231">HWY 231</option>
<option value="i-85">I-85</option>
<option value="i-59">I-59</option>
<option value="i-55">I-55</option>
<option value="hwy 63">Hwy 63</option>
<option value="i-30">I-30</option>
<option value="i-40">I-40</option>
<option value="hwy 67">HWY 67</option>
<option value="i-8">I-8</option>
<option value="i-15">I-15</option>
<option value="i-5">I-5</option>
<option value="hwy 99">Hwy 99</option>
<option value="hwy 58">Hwy 58</option>
<option value="i-70">I-70</option>
<option value="hwy 24">Hwy 24</option>
<option value="hwy 287">Hwy 287</option>
<option value="i-76">I-76</option>
<option value="hwy 287/50">Hwy 287/50</option>
<option value="i-25">I-25</option>
<option value="i-4">I-4</option>
<option value="i-95">I-95</option>
<option value="hwy 301">Hwy 301</option>
<option value="i-75">I-75</option>
<option value="hwy 27">Hwy 27</option>
<option value="i-16">I-16</option>
<option value="i-80">I-80</option>
<option value="i-35">I-35</option>
<option value="hwy 18">Hwy 18</option>
<option value="i-29">I-29</option>
<option value="i-84">I-84</option>
<option value="i-90">I-90</option>
<option value="i-57">I-57</option>
<option value="i-74">I-74</option>
<option value="i-64">I-64</option>
<option value="i-39">I-39</option>
<option value="i-94">I-94</option>
<option value="i-72">I-72</option>
<option value="i-69">I-69</option>
<option value="hwy 30">Hwy 30</option>
<option value="hwy 41">Hwy 41</option>
<option value="hwy 81">Hwy 81</option>
<option value="hwy 169">Hwy 169</option>
<option value="hwy 400">Hwy 400</option>
<option value="hwy 50">HWY 50</option>
<option value="hwy 50">Hwy 50</option>
<option value="hwy 54">Hwy 54</option>
<option value="i-135">I-135</option>
<option value="hwy 36">Hwy 36</option>
<option value="hwy 83">HWY 83</option>
<option value="i-24">I-24</option>
<option value="i-71">I-71</option>
<option value="hwy 190">Hwy 190</option>
<option value="i-68">I-68</option>
<option value="i-81">I-81</option>
<option value="hwy 370">Hwy 370</option>
<option value="i-49">I-49</option>
<option value="i-44">I-44</option>
<option value="hwy 61">Hwy 61</option>
<option value="hwy 60">Hwy 60</option>
<option value="hwy 82">Hwy 82</option>
<option value="hwy 49">Hwy 49</option>
<option value="hwy 45a">Hwy 45A</option>
<option value="hwy 2">Hwy 2</option>
<option value="hwy 275">Hwy 275</option>
<option value="i-295">I-295</option>
<option value="hwy 87">Hwy 87</option>
<option value="hwy 50/93">Hwy 50/93</option>
<option value="hwy 35">Hwy 35</option>
<option value="hwy 23">Hwy 23</option>
<option value="i-280">I-280</option>
<option value="hwy 30/23">Hwy 30/23</option>
<option value="hwy 69">Hwy 69</option>
<option value="hwy 412">Hwy 412</option>
<option value="hwy 74">Hwy 74</option>
<option value="hwy 19/76">Hwy 19/76</option>
<option value="hwy 75">Hwy 75</option>
<option value="hwy 70">Hwy 70</option>
<option value="i-78">I-78</option>
<option value="hwy 283">Hwy 283</option>
<option value="i-77">I-77</option>
<option value="i-26">I-26</option>
<option value="i-155">I-155</option>
<option value="i-240">I-240</option>
<option value="i-27">I-27</option>
<option value="hwy 385">Hwy 385</option>
<option value="hwy 288">Hwy 288</option>
<option value="hwy 225">Hwy 225</option>
<option value="hwy 59">Hwy 59</option>
<option value="hwy 287">HWY 287</option>
<option value="hwy 281">Hwy 281</option>
<option value="i-45">I-45</option>
<option value="i-35w">I-35W</option>
<option value="hwy 6">Hwy 6</option>
<option value="loop 610">Loop 610</option>
<option value="i-35e">I-35E</option>
<option value="hwy 77">Hwy 77</option>
<option value="hwy 59/69/loop 287">Hwy 59/69/Loop 287</option>
<option value="hwy 67">Hwy 67</option>
<option value="hwy 271">Hwy 271</option>
<option value="i-37">I-37</option>
<option value="i-82">I-82</option>
<option value="i-41">I-41</option>
<option value="i-43">I-43</option>
      </select>
      
      <label for="city">City</label>
      <select name="city">
        <option value="clanton">Clanton</option>
<option value="evergreen">Evergreen</option>        
<option value="falkville">Falkville</option>        
<option value="jasper">Jasper</option>
<option value="loxley">Loxley</option>
<option value="mccalla">McCalla</option>
<option value="moody">Moody</option>
<option value="muscle shoals">Muscle Shoals</option>
<option value="ozark">Ozark</option>
<option value="prichard">Prichard</option>
<option value="shorter">Shorter</option>
<option value="steele">Steele</option>
<option value="blytheville">Blytheville</option>    
<option value="jonesboro">Jonesboro</option>
<option value="little rock">Little Rock</option>
<option value="morrilton">Morrilton</option>
<option value="north little rock">North Little Rock</option>
<option value="palestine">Palestine</option>
<option value="prescott">Prescott</option>
<option value="searcy">Searcy</option>
<option value="west memphis">West Memphis</option>
<option value="benson">Benson</option>
<option value="buckeye">Buckeye</option>
<option value="casa grande">Casa Grande</option>
<option value="chandler ">Chandler </option>
<option value="gila bend">Gila Bend</option>
<option value="joseph city">Joseph City</option>
<option value="kingman">Kingman</option>
<option value="lake havasu city">Lake Havasu City</option>
<option value="quartzsite">Quartzsite</option>
<option value="tolleson">Tolleson</option>
<option value="williams">Williams</option>
<option value="yuma">Yuma</option>
<option value="barstow">Barstow</option>
<option value="coachella">Coachella</option>
<option value="corning">Corning</option>
<option value="lodi">Lodi</option>
<option value="lost hills ">Lost Hills </option>
<option value="ripon ">Ripon </option>
<option value="santa nella">Santa Nella</option>
<option value="tehachapi">Tehachapi</option>
<option value="tulare">Tulare</option>
<option value="bennett">Bennett</option>
<option value="buena vista">Buena Vista</option>
<option value="burlington">Burlington</option>
<option value="eads">Eads</option>
<option value="fountain">Fountain</option>
<option value="grand junction">Grand Junction</option>
<option value="gunnison">Gunnison</option>
<option value="hudson">Hudson</option>
<option value="la junta">La Junta</option>
<option value="lamar">Lamar</option>
<option value="monte vista">Monte Vista</option>
<option value="pueblo">Pueblo</option>
<option value="springfield">Springfield</option>
<option value="auburndale">Auburndale</option>
<option value="cottondale">Cottondale</option>
<option value="davenport">Davenport</option>
<option value="fort pierce">Fort Pierce</option>
<option value="hawthorne">Hawthorne</option>
<option value="jacksonville">Jacksonville</option>
<option value="lee ">Lee </option>
<option value="moore haven">Moore Haven</option>
<option value="mossy head">Mossy Head</option>
<option value="north fort myers">North Fort Myers</option>
<option value="ocala">Ocala</option>
<option value="ormond beach ">Ormond Beach </option>
<option value="brunswick">Brunswick</option>
<option value="dublin ">Dublin </option>
<option value="emerson">Emerson</option>
<option value="hogansville">Hogansville</option>
<option value="jackson">Jackson</option>
<option value="macon">Macon</option>
<option value="richmond hill ">Richmond Hill </option>
<option value="thomson">Thomson</option>
<option value="tifton">Tifton</option>
<option value="waco ">Waco </option>
<option value="clive">Clive</option>
<option value="ellsworth">Ellsworth</option>
<option value="floyd">Floyd</option>
<option value="newton ">Newton </option>
<option value="shelby">Shelby</option>
<option value="sioux city">Sioux City</option>
<option value="heyburn ">Heyburn </option>
<option value="idaho falls">Idaho Falls</option>
<option value="post falls">Post Falls</option>
<option value="dwight">Dwight</option>
<option value="greenup">Greenup</option>
<option value="greenville">Greenville</option>
<option value="hamel">Hamel</option>
<option value="ina">Ina</option>
<option value="kankakee">Kankakee</option>
<option value="knoxville">Knoxville</option>
<option value="le roy ">Le Roy </option>
<option value="new baden">New Baden</option>
<option value="oglesby">Oglesby</option>
<option value="roscoe">Roscoe</option>
<option value="south holland">South Holland</option>
<option value="south jacksonville">South Jacksonville</option>
<option value="utica ">Utica </option>
<option value="williamsville">Williamsville</option>
<option value="angola">Angola</option>
<option value="belleville">Belleville</option>
<option value="demotte">Demotte</option>
<option value="gary">Gary</option>
<option value="haubstadt">Haubstadt</option>
<option value="knightstown">Knightstown</option>
<option value="marion">Marion</option>
<option value="memphis ">Memphis </option>
<option value="pendleton">Pendleton</option>
<option value="pittsboro">Pittsboro</option>
<option value="plymouth">Plymouth</option>
<option value="richmond ">Richmond </option>
<option value="saint paul ">Saint Paul </option>
<option value="terre haute">Terre Haute</option>
<option value="whiteland">Whiteland</option>
<option value="whitestown">Whitestown</option>
<option value="woodburn">Woodburn</option>
<option value="arkansas city">Arkansas City</option>
<option value="chanute">Chanute</option>
<option value="colby">Colby</option>
<option value="cunningham">Cunningham</option>
<option value="dodge city">Dodge City</option>
<option value="ellis">Ellis</option>
<option value="garden city">Garden City</option>
<option value="great bend">Great Bend</option>
<option value="hays">Hays</option>
<option value="holcomb">Holcomb</option>
<option value="liberal">Liberal</option>
<option value="mcpherson">McPherson</option>
<option value="meade">Meade</option>
<option value="norton">Norton</option>
<option value="ottawa">Ottawa</option>
<option value="phillipsburg">Phillipsburg</option>
<option value="pratt">Pratt</option>
<option value="scott city">Scott City</option>
<option value="south hutchinson">South Hutchinson</option>
<option value="syracuse">Syracuse</option>
<option value="calvert city ">Calvert City </option>
<option value="corbin">Corbin</option>
<option value="grayson">Grayson</option>
<option value="horse cave">Horse Cave</option>
<option value="richmond">Richmond</option>
<option value="sadieville">Sadieville</option>
<option value="shepherdsville">Shepherdsville</option>
<option value="sparta">Sparta</option>
<option value="waddy ">Waddy </option>
<option value="duson">Duson</option>
<option value="greenwood">Greenwood</option>
<option value="lake charles">Lake Charles</option>
<option value="minden ">Minden </option>
<option value="port allen">Port Allen</option>
<option value="port barre">Port Barre</option>
<option value="tallulah">Tallulah</option>
<option value="vinton">Vinton</option>
<option value="cumberland">Cumberland</option>
<option value="hagerstown">Hagerstown</option>
<option value="marshall ">Marshall </option>
<option value="albert lea">Albert Lea</option>
<option value="bevier">Bevier</option>
<option value="bloomsdale">Bloomsdale</option>
<option value="boonville">Boonville</option>
<option value="bridgeton">Bridgeton</option>
<option value="eagleville">Eagleville</option>
<option value="harrisonville">Harrisonville</option>
<option value="joplin">Joplin</option>
<option value="matthews   ">Matthews   </option>
<option value="neosho">Neosho</option>
<option value="new london">New London</option>
<option value="rolla ">Rolla </option>
<option value="saint joseph">Saint Joseph</option>
<option value="saint louis">Saint Louis</option>
<option value="sikeston">Sikeston</option>
<option value="strafford">Strafford</option>
<option value="batesville">Batesville</option>
<option value="biloxi">Biloxi</option>
<option value="canton">Canton</option>
<option value="columbus">Columbus</option>
<option value="flowood">Flowood</option>
<option value="gulfport">Gulfport</option>
<option value="indianola">Indianola</option>
<option value="lake">Lake</option>
<option value="magee">Magee</option>
<option value="mccomb">McComb</option>
<option value="poplarville">Poplarville</option>
<option value="toomsuba ">Toomsuba </option>
<option value="tupelo">Tupelo</option>
<option value="west point">West Point</option>
<option value="hardin">Hardin</option>
<option value="dunn">Dunn</option>
<option value="salisbury">Salisbury</option>
<option value="fargo">Fargo</option>
<option value="williston">Williston</option>
<option value="aurora ">Aurora </option>
<option value="norfolk">Norfolk</option>
<option value="north platte">North Platte</option>
<option value="sidney">Sidney</option>
<option value="valley">Valley</option>
<option value="bordentown">Bordentown</option>
<option value="albuquerque">Albuquerque</option>
<option value="clayton">Clayton</option>
<option value="clovis">Clovis</option>
<option value="gallup">Gallup</option>
<option value="las cruces">Las Cruces</option>
<option value="lordsburg">Lordsburg</option>
<option value="milan">Milan</option>
<option value="santa rosa">Santa Rosa</option>
<option value="tucumcari">Tucumcari</option>
<option value="ely">Ely</option>
<option value="fernley">Fernley</option>
<option value="las vegas ">Las Vegas </option>
<option value="wells ">Wells </option>
<option value="binghamton">Binghamton</option>
<option value="canaan">Canaan</option>
<option value="bidwell">Bidwell</option>
<option value="burbank">Burbank</option>
<option value="circleville">Circleville</option>
<option value="conneaut">Conneaut</option>
<option value="dayton">Dayton</option>
<option value="hubbard">Hubbard</option>
<option value="jeffersonville ">Jeffersonville </option>
<option value="north baltimore">North Baltimore</option>
<option value="perrysburg">Perrysburg</option>
<option value="upper sandusky">Upper Sandusky</option>
<option value="zanesville">Zanesville</option>
<option value="ada">Ada</option>
<option value="altus">Altus</option>
<option value="alva">Alva</option>
<option value="ardmore">Ardmore</option>
<option value="atoka">Atoka</option>
<option value="beaver">Beaver</option>
<option value="boise city">Boise City</option>
<option value="broken bow">Broken Bow</option>
<option value="buffalo">Buffalo</option>
<option value="chickasha">Chickasha</option>
<option value="choctaw">Choctaw</option>
<option value="chouteau">Chouteau</option>
<option value="clinton">Clinton</option>
<option value="colbert ">Colbert </option>
<option value="comanche">Comanche</option>
<option value="crescent">Crescent</option>
<option value="duncan">Duncan</option>
<option value="durant">Durant</option>
<option value="el reno">El Reno</option>
<option value="elk city">Elk City</option>
<option value="enid">Enid</option>
<option value="erick">Erick</option>
<option value="eufaula">Eufaula</option>
<option value="fairview">Fairview</option>
<option value="guthrie">Guthrie</option>
<option value="guymon">Guymon</option>
<option value="hennessey">Hennessey</option>
<option value="henryetta">Henryetta</option>
<option value="hinton ">Hinton </option>
<option value="hollis">Hollis</option>
<option value="hooker">Hooker</option>
<option value="kingfisher">Kingfisher</option>
<option value="lawton">Lawton</option>
<option value="lindsay">Lindsay</option>
<option value="madill">Madill</option>
<option value="mangum">Mangum</option>
<option value="marlow">Marlow</option>
<option value="mcloud">McLoud</option>
<option value="miami">Miami</option>
<option value="norman">Norman</option>
<option value="nowata">Nowata</option>
<option value="okemah">Okemah</option>
<option value="oklahoma city">Oklahoma City</option>
<option value="okmulgee">Okmulgee</option>
<option value="pauls valley">Pauls Valley</option>
<option value="purcell">Purcell</option>
<option value="seminole">Seminole</option>
<option value="shawnee">Shawnee</option>
<option value="tahlequah">Tahlequah</option>
<option value="tecumseh">Tecumseh</option>
<option value="texhoma">Texhoma</option>
<option value="tonkawa ">Tonkawa </option>
<option value="union city">Union City</option>
<option value="valliant">Valliant</option>
<option value="watonga">Watonga</option>
<option value="webbers falls">Webbers Falls</option>
<option value="west siloam springs">West Siloam Springs</option>
<option value="woodward">Woodward</option>
<option value="yukon">Yukon</option>
<option value="boardman">Boardman</option>
<option value="ontario">Ontario</option>
<option value="roseburg">Roseburg</option>
<option value="troutdale">Troutdale</option>
<option value="carlisle">Carlisle</option>
<option value="hamburg">Hamburg</option>
<option value="jonestown ">Jonestown </option>
<option value="londonderry">Londonderry</option>
<option value="mifflinville ">Mifflinville </option>
<option value="blacksburg">Blacksburg</option>
<option value="cayce">Cayce</option>
<option value="dillon">Dillon</option>
<option value="fair play">Fair Play</option>
<option value="fort mill">Fort Mill</option>
<option value="lexington">Lexington</option>
<option value="newberry">Newberry</option>
<option value="orangeburg ">Orangeburg </option>
<option value="box elder">Box Elder</option>
<option value="sioux falls">Sioux Falls</option>
<option value="baxter ">Baxter </option>
<option value="charleston">Charleston</option>
<option value="christiana">Christiana</option>
<option value="columbia">Columbia</option>
<option value="dandridge">Dandridge</option>
<option value="dickson">Dickson</option>
<option value="dyersburg">Dyersburg</option>
<option value="lenoir city">Lenoir City</option>
<option value="memphis">Memphis</option>
<option value="nashville">Nashville</option>
<option value="nickajack lake">Nickajack Lake</option>
<option value="white house">White House</option>
<option value="amarillo">Amarillo</option>
<option value="andrews">Andrews</option>
<option value="angleton">Angleton</option>
<option value="anna">Anna</option>
<option value="anthony">Anthony</option>
<option value="baird">Baird</option>
<option value="baytown">Baytown</option>
<option value="claude">Claude</option>
<option value="cleveland ">Cleveland </option>
<option value="comfort">Comfort</option>
<option value="dallas">Dallas</option>
<option value="deer park">Deer Park</option>
<option value="denton">Denton</option>
<option value="domino">Domino</option>
<option value="dumas">Dumas</option>
<option value="edinburg">Edinburg</option>
<option value="edna">Edna</option>
<option value="el paso">El Paso</option>
<option value="encinal">Encinal</option>
<option value="fairfield">Fairfield</option>
<option value="fort stockton">Fort Stockton</option>
<option value="fort worth">Fort Worth</option>
<option value="hearne">Hearne</option>
<option value="hereford">Hereford</option>
<option value="hillsboro">Hillsboro</option>
<option value="houston">Houston</option>
<option value="hungerford">Hungerford</option>
<option value="hutchins">Hutchins</option>
<option value="italy">Italy</option>
<option value="katy">Katy</option>
<option value="kingsville ">Kingsville </option>
<option value="leary">Leary</option>
<option value="lubbock">Lubbock</option>
<option value="lufkin">Lufkin</option>
<option value="luling">Luling</option>
<option value="midland">Midland</option>
<option value="midlothian">Midlothian</option>
<option value="mount vernon">Mount Vernon</option>
<option value="natalia">Natalia</option>
<option value="odessa ">Odessa </option>
<option value="paris">Paris</option>
<option value="pecos">Pecos</option>
<option value="quanah">Quanah</option>
<option value="ranger">Ranger</option>
<option value="rhome">Rhome</option>
<option value="rockwall">Rockwall</option>
<option value="san antonio">San Antonio</option>
<option value="seguin">Seguin</option>
<option value="sinton">Sinton</option>
<option value="sweetwater">Sweetwater</option>
<option value="three rivers">Three Rivers</option>
<option value="van">Van</option>
<option value="van horn">Van Horn</option>
<option value="weatherford">Weatherford</option>
<option value="weimar">Weimar</option>
<option value="wichita falls">Wichita Falls</option>
<option value="willis">Willis</option>
<option value="brigham city">Brigham City</option>
<option value="cedar city ">Cedar City </option>
<option value="salina">Salina</option>
<option value="salt lake city">Salt Lake City</option>
<option value="springville">Springville</option>
<option value="franklin">Franklin</option>
<option value="lambsburg">Lambsburg</option>
<option value="max meadows">Max Meadows</option>
<option value="meadowview">Meadowview</option>
<option value="ruther glen">Ruther Glen</option>
<option value="skippers">Skippers</option>
<option value="south hill">South Hill</option>
<option value="tom's brook">Tom's Brook</option>
<option value="ellensburg">Ellensburg</option>
<option value="napavine">Napavine</option>
<option value="prosser">Prosser</option>
<option value="ritzville">Ritzville</option>
<option value="tacoma">Tacoma</option>
<option value="dekorra - poynette">Dekorra - Poynette</option>
<option value="fond du lac">Fond du Lac</option>
<option value="menomonie">Menomonie</option>
<option value="oak creek">Oak Creek</option>
<option value="oakdale">Oakdale</option>
<option value="sheboygan">Sheboygan</option>
<option value="ripley">Ripley</option>
<option value="cheyenne">Cheyenne</option>
<option value="wamsutter">Wamsutter</option>
      </select>

      <label for="state">State</label>
      <select name="state">
        <option value="al">AL</option>
<option value="ar">AR</option>
<option value="az">AZ</option>
<option value="ca">CA</option>
<option value="co">CO</option>
<option value="fl">FL</option>
<option value="ga">GA</option>
<option value="ia">IA</option>
<option value="id">ID</option>
<option value="il">IL</option>
<option value="in">IN</option>
<option value="ks">KS</option>
<option value="ky">KY</option>
<option value="la">LA</option>
<option value="md">MD</option>
<option value="mi">MI</option>
<option value="mn">MN</option>
<option value="mo">MO</option>
<option value="ms">MS</option>
<option value="mt">MT</option>
<option value="nc">NC</option>
<option value="nd">ND</option>
<option value="ne">NE</option>
<option value="nj">NJ</option>
<option value="nm">NM</option>
<option value="nv">NV</option>
<option value="ny">NY</option>
<option value="oh">OH</option>
<option value="ok">OK</option>
<option value="or">OR</option>
<option value="pa">PA</option>
<option value="sc">SC</option>
<option value="sd">SD</option>
<option value="tn">TN</option>
<option value="tx">TX</option>
<option value="ut">UT</option>
<option value="va">VA</option>
<option value="wa">WA</option>
<option value="wi">WI</option>
<option value="wv">WV</option>
<option value="wy">WY</option>
      </select>
    </div>
  </div>
</template>

<script>
export default {
  name: "locations",
};
</script>

<style>
.locations-container {
  margin: 60px;
}
</style>
